### ISSUE TITLE
Unknown identifier: valuesOf

### ISSUE THREAD

**Issue by griot-alpha** [AntonShuvaev/jet-client-support#17]
### Describe the Issue

Hi,

An issue found on "porting over" a working http-client API to JetClient. On request made that leads to a redirect (and with auto redirect disabled) I parse the redirect headers for the location header values.

On the http-client syntax, it works with the following:

`> {%
 client.global.set("redirect_URL", response.headers.valuesOf("Location")[0]);
%}`

And on the JetClient side, I have the following which I believe is correct

`jc.folderVariables.setLocalEnv("report_url", jc.response.headers.valuesOf("location")[0])`

but it generates the "Unknown identifier: valuesOf" error

It does seem to parse the command in the window properly in that the syntax checker correctly inserts the "name:" and "headerName" tags.

I get the same behavior on Linux and Windows clients and on different headers

### Steps to reproduce?

```Markdown
1. Add a `jc.folderVariables.setLocalEnv("report_url", jc.response.headers.valuesOf("location")[0])` command to parse response header and add to variable

2. Encounter error in log as indicated
```

### Operating System

Windows

### IDE

Pycharm 2023.1 (Professional Edition)

### JetClient version

2023.1.8

### Relevant log output

```Shell
2023-04-24 12:30:08,049 [8719623]   INFO - #io.jetclient.eL - Error while running script
TypeError: invokeMember (valuesOf) on io.jetclient.js.bindings.s failed due to: Unknown identifier: valuesOf
	at <js> :module:eval(test-script-45a36f6a.js:2:47-82)
	at org.graalvm.polyglot.Context.eval(Context.java:399)
	at io.jetclient.eL.a(SourceFile:271)
	at io.jetclient.eL.runTestsScript(SourceFile:216)
	at io.jetclient.a$c.completed(SourceFile:316)
	at io.jetclient.a$c.completed(SourceFile:290)
	at org.apache.hc.core5.concurrent.BasicFuture.completed(BasicFuture.java:123)
	at org.apache.hc.core5.concurrent.ComplexFuture.completed(ComplexFuture.java:72)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient$1$1.completed(InternalAbstractHttpAsyncClient.java:280)
	at org.apache.hc.core5.http.nio.support.AbstractAsyncResponseConsumer.consumeResponse(AbstractAsyncResponseConsumer.java:114)
	at org.apache.hc.client5.http.impl.async.InternalAbstractHttpAsyncClient$1.handleResponse(InternalAbstractHttpAsyncClient.java:275)
	at org.apache.hc.client5.http.impl.async.AsyncHttpRequestRetryExec$1.handleResponse(AsyncHttpRequestRetryExec.java:118)
	at org.apache.hc.client5.http.impl.async.AsyncProtocolExec$1.handleResponse(AsyncProtocolExec.java:230)
	at org.apache.hc.client5.http.impl.async.HttpAsyncMainClientExec$1.consumeResponse(HttpAsyncMainClientExec.java:210)
	at org.apache.hc.core5.http2.impl.nio.ClientH2StreamHandler.consumeHeader(ClientH2StreamHandler.java:212)
	at org.apache.hc.core5.http2.impl.nio.AbstractH2StreamMultiplexer$H2Stream.consumeHeader(AbstractH2StreamMultiplexer.java:1628)
	at org.apache.hc.core5.http2.impl.nio.AbstractH2StreamMultiplexer.consumeHeaderFrame(AbstractH2StreamMultiplexer.java:1108)
	at org.apache.hc.core5.http2.impl.nio.AbstractH2StreamMultiplexer.consumeFrame(AbstractH2StreamMultiplexer.java:783)
	at org.apache.hc.core5.http2.impl.nio.AbstractH2StreamMultiplexer.onInput(AbstractH2StreamMultiplexer.java:445)
	at org.apache.hc.core5.http2.impl.nio.AbstractH2IOEventHandler.inputReady(AbstractH2IOEventHandler.java:65)
	at org.apache.hc.core5.http2.impl.nio.ClientH2IOEventHandler.inputReady(ClientH2IOEventHandler.java:39)
	at org.apache.hc.core5.reactor.ssl.SSLIOSession.decryptData(SSLIOSession.java:600)
	at org.apache.hc.core5.reactor.ssl.SSLIOSession.access$200(SSLIOSession.java:74)
	at org.apache.hc.core5.reactor.ssl.SSLIOSession$1.inputReady(SSLIOSession.java:202)
	at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:142)
	at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:178)
	at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:127)
	at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86)
	at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by AntonShuvaev** [comment]
Hi,

The `ResponseHeaders` object doesn't have method `valuesOf`. The interface looks like:
```
interface ResponseHeaders {

    headers: Header[];

    get(name: string): string | null;

    getAll(name: string): string[];

    has(name: string): boolean;
}
```
So you need to use `getAll` method instead. 

I know that completion also suggests methods from HttpClient `ResponseHeaders`. I'll try to fix it.

**Comment by AntonShuvaev** [comment]
Closing this issue since the completion works as expected after updating IntelliJ to version 2023.1.1.
