### ISSUE TITLE
"Could not send request" Error

### ISSUE THREAD

**Issue by artemn** [AntonShuvaev/jet-client-support#90]
**Describe the bug**
I've imported the collection and environment from the postman.
Then I've defined variables successfully.
Then tried to run a query - getting an error.

Subscribed - still error.

```
class com.oracle.truffle.polyglot.PolyglotMap cannot be cast to class io.jetclient.js.bindings.p (com.oracle.truffle.polyglot.PolyglotMap and io.jetclient.js.bindings.p are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @462ff55c)
io.jetclient.dS: class com.oracle.truffle.polyglot.PolyglotMap cannot be cast to class io.jetclient.js.bindings.p (com.oracle.truffle.polyglot.PolyglotMap and io.jetclient.js.bindings.p are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @462ff55c)
	at io.jetclient.gd.a(SourceFile:107)
	at io.jetclient.gi.a(SourceFile:370)
	at io.jetclient.gi.a(SourceFile:241)
	at io.jetclient.t.a(SourceFile:309)
	at io.jetclient.t$l.run(SourceFile:267)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassCastException: class com.oracle.truffle.polyglot.PolyglotMap cannot be cast to class io.jetclient.js.bindings.p (com.oracle.truffle.polyglot.PolyglotMap and io.jetclient.js.bindings.p are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @462ff55c)
	at io.jetclient.js.bindings.HttpRequestBinding.updateState$JetClient_core(SourceFile:605)
	at io.jetclient.gi.a(SourceFile:368)
	... 32 more
```

**Steps to reproduce**
During the attempt to run the query - failing with the stack trace above.

**Expected behavior**
To be working.

**Environment information:**
- OS: Mac OS (M1)
- IDE version: PhpStorm IDE, last stable
- plugin version: last stable

**Comment by AntonShuvaev** [comment]
Thanks for reporting this issue. The Postman and JetClient script libraries are mostly similar, but there are some differences. It looks like your script has code like this:
```js
jc.request.headers.add({
    key: "foo",
    value: "bar"
});
```
Please replace it with:
```js
jc.request.addHeader("foo", "bar");
```
I will improve the error message to point to the exact line where the error occurs in the next update.

**Comment by artemn** [comment]
Works, thank you.

> I will improve the error message to point to the exact line where the error occurs in the next update.
And additionally will be great to take it in account during import.

I would suggest displaying hints which warn you about scripting spec. Doc is already in place, but lazy programmers will roll their eyes (as  I did (: ) when they need to make a search (:
